version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173" 
    volumes:
      - /usr/src/app
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "3000:3000"   
    environment:
      DATABASE_URL: $DOCKER_API_DATABASE_URL
      DB_HOST: $DOCKER_API_HOST
    depends_on:
      - db
    volumes:
      - /home/src/api
      
  db:
    image: postgres
    container_name: $DOCKER_DB_CONTAINER_NAME
    ports:
      - "8080:5432"  
    environment:
      POSTGRES_PASSWORD: $DOCKER_DB_PASSWORD
      POSTGRES_DB: $DOCKER_DB_NAME
      POSTGRES_USER: $DOCKER_DB_USER
    volumes:
      - ./postgres:/var/lib/postgres

  

    
